name: MIRNAPEX_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - snakemake-minimal
  - star
  - bedtools
  - samtools
  - pandas
  - numpy
  - scikit-learn
  - pyyaml
  - joblib
